# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 14:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=254)),
                ('url', models.URLField(max_length=254)),
                ('contact', models.EmailField(blank=True, max_length=254)),
                ('py_module', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PluginInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.Plugin')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=254)),
                ('url', models.URLField(max_length=254)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='component',
            old_name='urlfield',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='statuses',
            field=models.ManyToManyField(to='status.Status'),
        ),
        migrations.AddField(
            model_name='component',
            name='plugins',
            field=models.ManyToManyField(to='status.PluginInstance'),
        ),
    ]
