# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-22 18:58
from __future__ import unicode_literals

import defcon.status.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='time_end',
            field=models.DateTimeField(blank=True, default=defcon.status.models._default_time_end, null=True),
        ),
    ]
