# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20170413_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='plugins',
            field=models.ManyToManyField(blank=True, null=True, to='status.PluginInstance'),
        ),
    ]
