# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-23 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20171022_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='link',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='link',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='plugininstance',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='link',
            field=models.URLField(max_length=1024),
        ),
    ]
