# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-09 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20180223_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstance',
            name='failure',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='failure_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='success',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='success_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
