# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20170413_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='name',
            new_name='title',
        ),
    ]
