# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_auto_20170413_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.TextField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='component',
            name='plugins',
            field=models.ManyToManyField(blank=True, to='status.PluginInstance'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='description',
            field=models.TextField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='plugininstance',
            name='statuses',
            field=models.ManyToManyField(blank=True, to='status.Status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.TextField(blank=True, max_length=254),
        ),
    ]
