# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 15:50
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_auto_20170413_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstance',
            name='config',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
