# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_plugininstance_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='plugin',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='url',
            new_name='link',
        ),
    ]
