# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 08:17
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_auto_20170414_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='metadata',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
