# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0008_status_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='time_start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
