# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 08:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0009_auto_20170418_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='status',
        ),
        migrations.AddField(
            model_name='status',
            name='defcon',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
