# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0013_auto_20170418_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstance',
            name='description',
            field=models.TextField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='name',
            field=models.CharField(default='bla', max_length=64),
            preserve_default=False,
        ),
    ]
