name: Bump version

on:
  push:
    branches:
      - master

jobs:
  bump_version:
    if: ${{ !contains(github.event.head_commit.message, 'Bump version') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install bumpversion
        run: pip install bumpversion

      - name: Set git config
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"

      - name: Increment version
        run: bumpversion patch setup.py

      - name: Push changes
        run: |
          git push --set-upstream origin bump-version

      - name: Create Pull Request with Versioning Tag
        uses: peter-evans/create-pull-request@v3
        with:
          title: "[Deploy] Bump version for release"
          branch: "bump-version"
          base: "master"
          labels: "versioning"