name: Publish to PyPI

on:
  push:
    branches:
      - master

jobs:
  bump_version:
    if: ! contains(github.event.head_commit.message, 'Bump version')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install bumpversion
        run: pip install bumpversion

      - name: Set git config
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"

      - name: Increment version
        run: bumpversion patch setup.py

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        run: |
          git push origin HEAD:refs/heads/bump-version

      - name: Create Pull Request with Versioning Tag
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Bump version for release"
          branch: "version-bump"
          base: "master"
          labels: "versioning"

  deploy:
    if: contains(github.event.head_commit.message, 'Bump version')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install upload dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build package
        run: python setup.py sdist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages: dist/*.tar.gz dist/*.whl
